[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "2.2.2", features = ["postgres_backend", "postgres"] }
rocket = { version = "0.5.1", features = ["json"] }
